# Generated by Django 3.1.1 on 2020-11-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201122_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='swipe',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='user',
        ),
        migrations.AddField(
            model_name='swipe',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
    ]
