# Generated by Django 3.1.1 on 2020-12-23 10:39

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201216_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
