# Generated by Django 3.1.1 on 2020-11-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20201122_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to='Profile.Profile'),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipe', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='swiped',
            field=models.ManyToManyField(blank=True, related_name='swiped', to='Profile.Profile'),
        ),
    ]
