# Generated by Django 3.1.1 on 2020-11-23 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0005_auto_20201123_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipe',
            name='profile',
        ),
        migrations.AddField(
            model_name='swipe',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
