# Generated by Django 3.1.1 on 2020-12-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20201225_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cropping',
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
