# Generated by Django 3.1.1 on 2020-12-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20201225_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
    ]
