# Generated by Django 3.1.1 on 2020-12-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_auto_20201205_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foreign_lan',
            new_name='foreign_lan1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='freeday',
            new_name='freeday1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='native_lan',
            new_name='native_lan1',
        ),
        migrations.AddField(
            model_name='profile',
            name='foreign_lan2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='foreign_lan3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='freeday2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='freeday3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='native_lan2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='native_lan3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
