# Generated by Django 3.1.1 on 2020-12-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_auto_20201215_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foreign_lan1',
            new_name='foreign_lan',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='freeday1',
            new_name='freeday',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='native_lan1',
            new_name='native_lan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foreign_lan2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foreign_lan3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='freeday2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='freeday3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='native_lan2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='native_lan3',
        ),
    ]
